on: push
jobs:
  test_create_dataset:
    runs-on: ubuntu-latest
    container: node:lts-bookworm
    env:
      FOUNDRY_TOKEN: ${{secrets.FOUNDRY_TOKEN}}
      PALANTIR_HOSTNAME: ${{secrets.PALANTIR_HOSTNAME}}
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: ./src/datasets/create_dataset
        with:
          datasetName: "CICD_Test"
          parentFolderRid: ${{secrets.FOLDER_RID}}
      - uses: ./src/datasets/create_branch
        with:
          branchName: TestBranch
          datasetRid: ${{secrets.DATASET_RID}}