on: push
jobs:
  test_create_dataset:
    runs-on: ubuntu-latest
    container: node:lts-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: ./src/datasets/create_dataset
        with:
          datasetName: "CICD_Test"
          foundry_token: ${{secrets.FOUNDRY_TOKEN}}
          palantir_hostname: ${{secrets.PALANTIR_HOSTNAME}}
          parentFolderRid: ${{secrets.FOLDER_RID}}